In [1]:
import pandas as pd

In [2]:
combined_data = pd.read_csv('./combined_data.csv')
combined_data

,Date,No.,Learners' ID,Full Name_x,IC,Year,Age,Gender,Nationality,Ethnic,...,Status,NPS,Satisfaction scores,value-time-spent,Content,Instructor,Experience,Attendance rate,Final project score (Fail/ Pass/ scores),Placement Status
0,2023,3138,LN20233138,Az Khaizuran Azman,971021-21-6725,27,26-35,Male,Malaysian,Bumiputera Malay,...,Graduated,8.0,4.0,4.0,4.0,5.0,4.0,100.0,Completed,NaN
1,2023,3134,LN20233134,Deilan Raj Victor Jonathan,990709-09-5289,25,18-25,Male,Malaysian,Indian,...,Graduated,8.0,4.0,5.0,4.7,3.8,2.5,100.0,Completed,Permanent
2,2023,3132,LN20233132,Emir Aizat Bin Abd Rashid,950818-18-6401,29,26-35,Male,Malaysian,Bumiputera Malay,...,Graduated,5.0,3.0,3.0,2.7,3.3,3.5,93.0,Completed,Permanent
3,2023,3144,LN20233144,Hasanatul Aliah Binti Saifullah,990922-22-5374,25,18-25,Female,Malaysian,Bumiputera Malay,...,Graduated,8.0,4.0,5.0,4.7,4.5,5.0,100.0,Completed,Permanent
4,2023,3137,LN20233137,Mohamad Syahafizin Bin Mohamad Azahar,960903-03-5111,28,26-35,Male,Malaysian,Bumiputera Malay,...,Graduated,7.0,3.0,4.0,3.0,3.3,3.0,100.0,Completed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,2023,3643,LN20233643,Shaan Gom,980521-21-5359,26,26-35,Male,Malaysian,Others,...,Graduated,6.0,3.0,3.0,3.0,3.8,3.0,100.0,Completed,Contract
808,2023,3644,LN20233644,Tan Hong Liang,980317-17-6593,26,26-35,Male,Malaysian,Chinese,...,Graduated,10.0,5.0,4.0,5.0,5.0,4.5,93.0,Completed,Permanent
809,2023,3645,LN20233645,Teck Waye Diong,971005-05-5285,27,26-35,Male,Malaysian,Chinese,...,Graduated,8.0,4.0,3.0,3.0,3.5,4.0,100.0,Completed,Permanent
810,2023,3646,LN20233646,Ungku Nur Aqilah Hidayah Binti Ungku A Halim,991021-21-5806,25,18-25,Female,Malaysian,Bumiputera Malay,...,Graduated,10.0,5.0,5.0,5.0,5.0,5.0,100.0,Completed,Permanent
811,2023,3647,LN20233647,Wan Adri Syafi Bin Wan Mahadi,991114-14-5077,25,18-25,Male,Malaysian,Bumiputera Malay,...,Drop Out,9.2,4.8,4.3,4.6,4.8,4.6,0.0,NaN,Withdraw - Others

In [3]:
combined_data['Placement Status '].value_counts()

Placement Status
Permanent            423
Contract             161
Further study         23
Self-employment       19
Withdraw - Health      7
Withdraw - Others      6
Others                 4
Name: count, dtype: int64

In [4]:
combined_data.columns

Index(['Date', 'No.', 'Learners' ID', 'Full Name_x', 'IC', 'Year', 'Age',
       'Gender', 'Nationality', 'Ethnic', 'State of residence', 'Email',
       'Phone', 'LinkedIn', 'What is your primary reason of enrolling?',
       'Current proficiency of the topics/skills',
       'How did you hear about this programme?', 'Employment Status',
       'Years of work experience', 'Industry', 'Role Title',
       'Last drawn monthly salary', 'Education', 'University Course Name',
       'Field of Study', 'Field of Study (Others)', 'Type of Institution',
       'University Name', 'University Name (Others)', 'CGPA',
       'Graduating Year', 'Household income', 'Recipient of Government Aids',
       'What are the 3 factors that are most important to you for learning? (provide a list of 1, 2 and 3)',
       'What are the 3 factors that are most important for your career? (provide a list of 1, 2 and 3)',
       'What challenges to learning do you anticipate?',
       'What type of learning support do you need?',
       'How many jobs have your applied for in the past 30 days?',
       'What are the top (most common) 3 roles you've applied for?',
       'How many interviews have you attended?',
       'What are your top 3 preferred work locations?',
       'What is the top 3 factor when you’re considering a job?', 'Segment',
       'Course ID (1)', 'Status', 'NPS', 'Satisfaction scores',
       'value-time-spent', 'Content', 'Instructor', 'Experience',
       'Attendance rate', 'Final project score (Fail/ Pass/ scores)',
       'Placement Status '],
      dtype='object')

In [5]:
# Define the eligibility criteria
def passing_score(score):
    if isinstance(score, str):
        # Check if the value is 'completed'
        if score.lower().strip() == 'completed':
            return True  # Not a passing score
        else:
            try:
                score = float(score.rstrip('%'))
                return score >= 55
            except ValueError:
                return False  # Non-numeric string
    elif isinstance(score, (int, float)):
        return score >= 55
    else:
        return False
    
combined_data['Placement Status '] = combined_data['Placement Status '].str.strip( )

completed_finalproject = combined_data['Final project score (Fail/ Pass/ scores)'].apply(passing_score)
achieve_attendance = combined_data['Attendance rate'] >= 80
placement_status = combined_data['Placement Status '].isin(['Permanent', 'Contract', 'Self-employment'])

# Combine the criteria to determine eligibility
combined_data['Cert Eligibility'] = completed_finalproject & achieve_attendance & placement_status

In [6]:
combined_data[combined_data['Cert Eligibility']==False]

,Date,No.,Learners' ID,Full Name_x,IC,Year,Age,Gender,Nationality,Ethnic,...,NPS,Satisfaction scores,value-time-spent,Content,Instructor,Experience,Attendance rate,Final project score (Fail/ Pass/ scores),Placement Status,Cert Eligibility
0,2023,3138,LN20233138,Az Khaizuran Azman,971021-21-6725,27,26-35,Male,Malaysian,Bumiputera Malay,...,8.0,4.0,4.0,4.0,5.0,4.0,100.0,Completed,NaN,False
4,2023,3137,LN20233137,Mohamad Syahafizin Bin Mohamad Azahar,960903-03-5111,28,26-35,Male,Malaysian,Bumiputera Malay,...,7.0,3.0,4.0,3.0,3.3,3.0,100.0,Completed,NaN,False
7,2023,3139,LN20233139,Muhammad Akram Bin Omar,960309-09-6083,28,26-35,Male,Malaysian,Bumiputera Malay,...,8.0,5.0,4.0,4.0,5.0,4.5,100.0,Completed,Withdraw - Health,False
8,2023,3133,LN20233133,Muhammad Amir Fitri Bin Jamaludin,960314-14-5981,28,26-35,Male,Malaysian,Bumiputera Malay,...,9.0,5.0,5.0,5.0,5.0,5.0,100.0,Completed,NaN,False
20,2023,3221,LN20233221,Amein Ahmad,001101-01-0047,24,18-25,Male,Malaysian,Bumiputera Malay,...,10.0,5.0,5.0,5.0,5.0,5.0,94.0,Completed,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,2023,3632,LN20233632,Woon Yong Jiang,020622-22-1681,22,18-25,Male,Malaysian,Chinese,...,8.0,3.0,3.0,3.0,2.8,3.0,100.0,Completed,Further study,False
798,2023,3634,LN20233634,Aidil Haqeemy Bin Mohammad Johar,980409-09-6203,26,26-35,Male,Malaysian,Bumiputera Malay,...,9.0,5.0,4.0,4.3,4.8,5.0,100.0,Completed,NaN,False
803,2023,3639,LN20233639,Mohammad Afiq Bin Saharuddin,010610-10-0253,23,18-25,Male,Malaysian,Others,...,9.2,4.8,4.3,4.6,4.8,4.6,0.0,NaN,Withdraw - Others,False
804,2023,3640,LN20233640,Muhammad Asyraf Bin Azmi,930221-21-5115,31,26-35,Male,Malaysian,Bumiputera Malay,...,9.0,5.0,5.0,5.0,5.0,4.5,100.0,Completed,NaN,False
811,2023,3647,LN20233647,Wan Adri Syafi Bin Wan Mahadi,991114-14-5077,25,18-25,Male,Malaysian,Bumiputera Malay,...,9.2,4.8,4.3,4.6,4.8,4.6,0.0,NaN,Withdraw - Others,False