In [20]:
import pandas as pd

# Define the eligibility criteria
def passing_score(score):
    if isinstance(score, str):  # Check if the value is 'completed'
        if score.lower().strip( ) == 'completed':
            return True  
        else:
            try:
                score = float(score.rstrip('%'))
                return score >= 55
            except ValueError:
                return False  
    elif isinstance(score, (int, float)):
        return score >= 55
    else:
        return False

def check_eligibility(df, output_file):
    completed_finalproject = df['Final project score (Fail/ Pass/ scores)'].apply(passing_score)
    achieve_attendance = df['Attendance rate'] >= 80
    placement_status = df['Placement Status '].isin(['Permanent', 'Contract', 'Self-employment'])
   
    # Combine the criteria to determine eligibility
    df['Cert Eligibility'] = completed_finalproject & achieve_attendance & placement_status
    
    df.to_csv(output_file, index=False)
    print("Certificate eligibility check completed.")
    
    return df

if __name__ == "__main__":
    # to enter input and output file paths
    input_file = input("Enter the location of input CSV file: ")
    output_file = input("Enter the location of output CSV file: ")
    
    # Read input CSV to define df
    df = pd.read_csv(input_file)
    
    # Run certificate eligibility check
    modified_df = check_eligibility(df, output_file)

Enter the location of input CSV file: combined_data.csv
Enter the location of output CSV file: output.csv
Certificate eligibility check completed.

In [19]:
modified_df

,Date,No.,Learners' ID,Full Name_x,IC,Year,Age,Gender,Nationality,Ethnic,...,Status,NPS,Satisfaction scores,value-time-spent,Content,Instructor,Experience,Attendance rate,Final project score (Fail/ Pass/ scores),Placement Status
0,2023,3138,LN20233138,Az Khaizuran Azman,971021-21-6725,27,26-35,Male,Malaysian,Bumiputera Malay,...,Graduated,8.0,4.0,4.0,4.0,5.0,4.0,100.0,Completed,NaN
1,2023,3134,LN20233134,Deilan Raj Victor Jonathan,990709-09-5289,25,18-25,Male,Malaysian,Indian,...,Graduated,8.0,4.0,5.0,4.7,3.8,2.5,100.0,Completed,Permanent
2,2023,3132,LN20233132,Emir Aizat Bin Abd Rashid,950818-18-6401,29,26-35,Male,Malaysian,Bumiputera Malay,...,Graduated,5.0,3.0,3.0,2.7,3.3,3.5,93.0,Completed,Permanent
3,2023,3144,LN20233144,Hasanatul Aliah Binti Saifullah,990922-22-5374,25,18-25,Female,Malaysian,Bumiputera Malay,...,Graduated,8.0,4.0,5.0,4.7,4.5,5.0,100.0,Completed,Permanent
4,2023,3137,LN20233137,Mohamad Syahafizin Bin Mohamad Azahar,960903-03-5111,28,26-35,Male,Malaysian,Bumiputera Malay,...,Graduated,7.0,3.0,4.0,3.0,3.3,3.0,100.0,Completed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,2023,3643,LN20233643,Shaan Gom,980521-21-5359,26,26-35,Male,Malaysian,Others,...,Graduated,6.0,3.0,3.0,3.0,3.8,3.0,100.0,Completed,Contract
808,2023,3644,LN20233644,Tan Hong Liang,980317-17-6593,26,26-35,Male,Malaysian,Chinese,...,Graduated,10.0,5.0,4.0,5.0,5.0,4.5,93.0,Completed,Permanent
809,2023,3645,LN20233645,Teck Waye Diong,971005-05-5285,27,26-35,Male,Malaysian,Chinese,...,Graduated,8.0,4.0,3.0,3.0,3.5,4.0,100.0,Completed,Permanent
810,2023,3646,LN20233646,Ungku Nur Aqilah Hidayah Binti Ungku A Halim,991021-21-5806,25,18-25,Female,Malaysian,Bumiputera Malay,...,Graduated,10.0,5.0,5.0,5.0,5.0,5.0,100.0,Completed,Permanent
811,2023,3647,LN20233647,Wan Adri Syafi Bin Wan Mahadi,991114-14-5077,25,18-25,Male,Malaysian,Bumiputera Malay,...,Drop Out,9.2,4.8,4.3,4.6,4.8,4.6,0.0,NaN,Withdraw - Others